*&---------------------------------------------------------------------*
*&  Include           ZCAGS_CI_SEL_SCREEN
*&---------------------------------------------------------------------*

SELECTION-SCREEN: BEGIN OF BLOCK 001 WITH FRAME TITLE text-001.
SELECT-OPTIONS: pr_pckg FOR tdevc-devclass NO INTERVALS MODIF ID xc2.
PARAMETERS: pr_1_1 RADIOBUTTON GROUP gr_1 USER-COMMAND flg DEFAULT 'X'.
PARAMETERS: pr_1_2 RADIOBUTTON GROUP gr_1.
SELECTION-SCREEN: END OF BLOCK 001.

SELECTION-SCREEN: BEGIN OF BLOCK 002 WITH FRAME TITLE text-002.
PARAMETERS: pr_2_1 RADIOBUTTON GROUP gr_2 USER-COMMAND flg DEFAULT 'X'.
PARAMETERS: pr_2_2 RADIOBUTTON GROUP gr_2.
SELECTION-SCREEN: END OF BLOCK 002.

SELECTION-SCREEN: BEGIN OF BLOCK 003 WITH FRAME TITLE text-003.
PARAMETERS: pr_3_1 RADIOBUTTON GROUP gr_3 USER-COMMAND flg DEFAULT 'X'.
PARAMETERS: pr_3_2 RADIOBUTTON GROUP gr_3.
PARAMETERS: pr_3_3 RADIOBUTTON GROUP gr_3.
SELECTION-SCREEN: END OF BLOCK 003.

SELECTION-SCREEN: BEGIN OF BLOCK 004 WITH FRAME TITLE text-004.
PARAMETERS: p_tst_u TYPE string.
PARAMETERS: p_tst_p TYPE string.
PARAMETERS: p_cov_u TYPE string.
PARAMETERS: p_cov_p TYPE string.
SELECTION-SCREEN: END OF BLOCK 004.

SELECTION-SCREEN: BEGIN OF BLOCK 005 WITH FRAME TITLE text-005.
PARAMETERS: p_dir_l TYPE string DEFAULT '\\SAP-IFACE01.ST.STATOIL.NO\TRANS\ERPDEV\'.
PARAMETERS: p_dir_r TYPE string.
PARAMETERS: p_mail AS CHECKBOX DEFAULT 'X' TYPE abap_bool.
SELECTION-SCREEN: END OF BLOCK 005.

SELECTION-SCREEN: BEGIN OF BLOCK 006 WITH FRAME TITLE text-006.

SELECTION-SCREEN: END OF BLOCK 006.
